from collections.abc import Sequence

import numpy as np
import numpy.typing as npt

from .types import (
    ColorCameraParams,
    DeviceConfig,
    IrCameraParams,
    LedSettings,
    ReplayCalibration,
)

type _FrameArray = npt.NDArray[np.uint8] | npt.NDArray[np.float32]

def core_version() -> str: ...
def core_api_version() -> int: ...
def core_revision() -> str: ...
def compiled_pipelines() -> frozenset[str]: ...
def available_pipelines() -> frozenset[str]: ...

class NativePipeline:
    def __init__(self, name: str, device_id: int = -1) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def is_consumed(self) -> bool: ...
    def depth_p0_tables(self) -> npt.NDArray[np.uint8]: ...
    def depth_x_table(self) -> npt.NDArray[np.float32]: ...
    def depth_z_table(self) -> npt.NDArray[np.float32]: ...
    def depth_lookup_table(self) -> npt.NDArray[np.int16]: ...

class NativeFrame:
    @staticmethod
    def allocate(
        width: int,
        height: int,
        bytes_per_pixel: int,
        frame_type: int = -1,
        frame_format: int = 0,
        timestamp: int = 0,
        sequence: int = 0,
        exposure: float = 0.0,
        gain: float = 0.0,
        gamma: float = 0.0,
        status: int = 0,
    ) -> NativeFrame: ...
    @staticmethod
    def from_array(
        array: _FrameArray,
        frame_type: int = -1,
        frame_format: int = 0,
        timestamp: int = 0,
        sequence: int = 0,
        exposure: float = 0.0,
        gain: float = 0.0,
        gamma: float = 0.0,
        status: int = 0,
    ) -> NativeFrame: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def bytes_per_pixel(self) -> int: ...
    @property
    def timestamp(self) -> int: ...
    @property
    def sequence(self) -> int: ...
    @property
    def exposure(self) -> float: ...
    @property
    def gain(self) -> float: ...
    @property
    def gamma(self) -> float: ...
    @property
    def status(self) -> int: ...
    @property
    def format(self) -> int: ...
    @property
    def type(self) -> int: ...
    def to_numpy(self, copy: bool = False) -> _FrameArray: ...

class NativeFrameSet:
    def get(self, frame_type: int) -> NativeFrame: ...
    def contains(self, frame_type: int) -> bool: ...
    def release(self) -> None: ...
    @property
    def is_released(self) -> bool: ...
    @property
    def release_complete(self) -> bool: ...
    @property
    def entry_count(self) -> int: ...

def _testing_frame_set() -> NativeFrameSet: ...

class NativeSyncFrameListener:
    def __init__(self, frame_types: int) -> None: ...
    @property
    def _listener_address(self) -> int: ...
    def has_new_frame(self) -> bool: ...
    def wait(self, timeout: float | None = None) -> NativeFrameSet: ...

class NativeDeviceHandle:
    @property
    def serial_number(self) -> str: ...
    @property
    def firmware_version(self) -> str: ...
    @property
    def pipeline_name(self) -> str: ...
    def color_camera_params(self) -> dict[str, float]: ...
    def ir_camera_params(self) -> dict[str, float]: ...
    def set_color_camera_params(self, params: ColorCameraParams) -> None: ...
    def set_ir_camera_params(self, params: IrCameraParams) -> None: ...
    def set_configuration(self, config: DeviceConfig) -> None: ...
    def set_color_listener(self, listener: NativeSyncFrameListener) -> None: ...
    def set_depth_listener(self, listener: NativeSyncFrameListener) -> None: ...
    def set_color_auto_exposure(self, compensation: float = 0.0) -> None: ...
    def set_color_semi_auto_exposure(self, exposure_time_ms: float) -> None: ...
    def set_color_manual_exposure(
        self, integration_time_ms: float, analog_gain: float
    ) -> None: ...
    def set_color_setting(self, command: int, value: int | float) -> None: ...
    def get_color_setting(
        self, command: int, as_float: bool = False
    ) -> int | float: ...
    def set_led_status(self, settings: LedSettings) -> None: ...
    def start(self, rgb: bool = True, depth: bool = True) -> None: ...
    def stop(self) -> None: ...
    def close(self) -> None: ...
    @property
    def is_running(self) -> bool: ...
    @property
    def is_closed(self) -> bool: ...

class NativeFreenect2Context:
    def enumerate_devices(self) -> int: ...
    def device_serial_number(self, index: int) -> str: ...
    def default_device_serial_number(self) -> str: ...
    def open_device(
        self, name: str | int | None = None, pipeline: NativePipeline | None = None
    ) -> NativeDeviceHandle: ...

class NativeReplayContext:
    def open_device(
        self,
        filenames: Sequence[str],
        calibration: ReplayCalibration | None = None,
        pipeline: NativePipeline | None = None,
    ) -> NativeDeviceHandle: ...

class NativeRegistrationHandle:
    def __init__(
        self, ir_params: IrCameraParams, color_params: ColorCameraParams
    ) -> None: ...
    def apply_point(self, dx: int, dy: int, dz: float) -> tuple[float, float]: ...
    def apply(
        self,
        rgb: NativeFrame,
        depth: NativeFrame,
        undistorted: NativeFrame,
        registered: NativeFrame,
        enable_filter: bool = True,
        bigdepth: NativeFrame | None = None,
        color_depth_map: npt.NDArray[np.int32] | None = None,
    ) -> None: ...
    def undistort_depth(self, depth: NativeFrame, undistorted: NativeFrame) -> None: ...
    def point_xyz(
        self, undistorted: NativeFrame, row: int, column: int
    ) -> tuple[float, float, float]: ...
    def point_xyz_rgb(
        self, undistorted: NativeFrame, registered: NativeFrame, row: int, column: int
    ) -> tuple[float, float, float, int, int, int]: ...

def default_logger_level() -> int: ...
def logger_level_name(level: int) -> str: ...
def global_logger_level() -> int | None: ...
def set_global_log_level(level: int | None = None) -> None: ...
