from collections.abc import Sequence
from typing import Final, TypedDict

import numpy as np
import numpy.typing as npt

from .types import (
    ColorCameraParams,
    DeviceConfig,
    IrCameraParams,
    LedSettings,
    ProjectiveCameraModel,
    ProjectiveRegistrationOptions,
    ReplayCalibration,
    ReplayOptions,
)

type _FrameArray = npt.NDArray[np.uint8] | npt.NDArray[np.float32]

class _StreamRuntimeStatsDict(TypedDict):
    decoded_frames: int
    status_error_frames: int
    sequence_gaps: int
    last_sequence: int
    last_device_timestamp: int
    last_arrival_timestamp_us: int

class _DeviceRuntimeStatsDict(TypedDict):
    color: _StreamRuntimeStatsDict
    ir: _StreamRuntimeStatsDict
    depth: _StreamRuntimeStatsDict
    start_attempts: int
    successful_starts: int
    stop_calls: int
    disconnect_events: int
    transfer_stall_events: int

RGB_DECODER_VALUES: Final[dict[str, int]]

def core_version() -> str: ...
def core_api_version() -> int: ...
def core_revision() -> str: ...
def compiled_pipelines() -> frozenset[str]: ...
def available_pipelines() -> frozenset[str]: ...
def scale_projective_camera_model(
    model: ProjectiveCameraModel, width: int, height: int
) -> dict[str, object]: ...
def rectify_projective_camera_model(
    model: ProjectiveCameraModel,
) -> dict[str, object]: ...

class NativePipeline:
    def __init__(
        self,
        name: str,
        device_id: int = -1,
        rgb_decoder: int = 0,
        vaapi_device: str | None = None,
        allow_fallback: bool = True,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def is_consumed(self) -> bool: ...
    def depth_p0_tables(self) -> npt.NDArray[np.uint8]: ...
    def depth_x_table(self) -> npt.NDArray[np.float32]: ...
    def depth_z_table(self) -> npt.NDArray[np.float32]: ...
    def depth_lookup_table(self) -> npt.NDArray[np.int16]: ...

class NativeFrame:
    @staticmethod
    def allocate(
        width: int,
        height: int,
        bytes_per_pixel: int,
        frame_type: int = -1,
        frame_format: int = 0,
        timestamp: int = 0,
        sequence: int = 0,
        arrival_timestamp_us: int = 0,
        exposure: float = 0.0,
        gain: float = 0.0,
        gamma: float = 0.0,
        status: int = 0,
    ) -> NativeFrame: ...
    @staticmethod
    def from_array(
        array: _FrameArray,
        frame_type: int = -1,
        frame_format: int = 0,
        timestamp: int = 0,
        sequence: int = 0,
        arrival_timestamp_us: int = 0,
        exposure: float = 0.0,
        gain: float = 0.0,
        gamma: float = 0.0,
        status: int = 0,
    ) -> NativeFrame: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def bytes_per_pixel(self) -> int: ...
    @property
    def timestamp(self) -> int: ...
    @property
    def arrival_timestamp_us(self) -> int: ...
    @property
    def sequence(self) -> int: ...
    @property
    def exposure(self) -> float: ...
    @property
    def gain(self) -> float: ...
    @property
    def gamma(self) -> float: ...
    @property
    def status(self) -> int: ...
    @property
    def format(self) -> int: ...
    @property
    def type(self) -> int: ...
    def to_numpy(self, copy: bool = False) -> _FrameArray: ...
    def to_color(
        self, output: npt.NDArray[np.uint8], order: int
    ) -> npt.NDArray[np.uint8]: ...

class NativeFrameSet:
    def get(self, frame_type: int) -> NativeFrame: ...
    def contains(self, frame_type: int) -> bool: ...
    def release(self) -> None: ...
    @property
    def is_released(self) -> bool: ...
    @property
    def release_complete(self) -> bool: ...
    @property
    def entry_count(self) -> int: ...
    @property
    def delta_ticks(self) -> int | None: ...

def _testing_frame_set() -> NativeFrameSet: ...

class NativeSyncFrameListener:
    def __init__(self, frame_types: int) -> None: ...
    @property
    def _listener_address(self) -> int: ...
    def has_new_frame(self) -> bool: ...
    def wait(self, timeout: float | None = None) -> NativeFrameSet: ...

class NativeAlignedFrameListener:
    def __init__(
        self, frame_types: int, max_delta_ticks: int, queue_capacity: int = 8
    ) -> None: ...
    @property
    def _listener_address(self) -> int: ...
    def has_new_frame(self) -> bool: ...
    def wait(self, timeout: float | None = None) -> NativeFrameSet: ...
    def statistics(self) -> dict[str, int]: ...
    def _testing_push(self, frame_type: int, frame: NativeFrame) -> bool: ...

class NativeDeviceHandle:
    @property
    def serial_number(self) -> str: ...
    @property
    def firmware_version(self) -> str: ...
    @property
    def pipeline_name(self) -> str: ...
    @property
    def state(self) -> int: ...
    @property
    def last_error(self) -> str: ...
    def color_camera_params(self) -> dict[str, float]: ...
    def ir_camera_params(self) -> dict[str, float]: ...
    def runtime_statistics(self) -> _DeviceRuntimeStatsDict: ...
    def calibration_profile(self) -> NativeCalibrationProfileHandle | None: ...
    def set_color_camera_params(self, params: ColorCameraParams) -> None: ...
    def set_ir_camera_params(self, params: IrCameraParams) -> None: ...
    def set_configuration(self, config: DeviceConfig) -> None: ...
    def set_color_listener(
        self,
        listener: NativeSyncFrameListener
        | NativeAlignedFrameListener
        | NativeRecordingWriterHandle,
    ) -> None: ...
    def set_depth_listener(
        self,
        listener: NativeSyncFrameListener
        | NativeAlignedFrameListener
        | NativeRecordingWriterHandle,
    ) -> None: ...
    def set_color_auto_exposure(self, compensation: float = 0.0) -> None: ...
    def set_color_semi_auto_exposure(self, exposure_time_ms: float) -> None: ...
    def set_color_manual_exposure(
        self, integration_time_ms: float, analog_gain: float
    ) -> None: ...
    def set_color_setting(self, command: int, value: int | float) -> None: ...
    def get_color_setting(
        self, command: int, as_float: bool = False
    ) -> int | float: ...
    def set_led_status(self, settings: LedSettings) -> None: ...
    def start(self, rgb: bool = True, depth: bool = True) -> None: ...
    def stop(self) -> None: ...
    def close(self) -> None: ...
    @property
    def is_running(self) -> bool: ...
    @property
    def is_closed(self) -> bool: ...

class NativeFreenect2Context:
    def enumerate_devices(self) -> int: ...
    def device_serial_number(self, index: int) -> str: ...
    def default_device_serial_number(self) -> str: ...
    def wait_for_device(
        self, serial: str, timeout: float, poll_interval: float = 0.25
    ) -> bool: ...
    def open_device(
        self, name: str | int | None = None, pipeline: NativePipeline | None = None
    ) -> NativeDeviceHandle: ...

class NativeReplayContext:
    def open_device(
        self,
        filenames: Sequence[str],
        calibration: ReplayCalibration | None = None,
        pipeline: NativePipeline | None = None,
    ) -> NativeDeviceHandle: ...
    def open_recording(
        self,
        path: str,
        options: ReplayOptions,
        pipeline: NativePipeline | None = None,
    ) -> NativeDeviceHandle: ...

class NativeCalibrationProfileHandle:
    @staticmethod
    def load(path: str) -> NativeCalibrationProfileHandle: ...
    def save(self, path: str) -> None: ...
    def check_device(
        self,
        serial: str,
        firmware: str,
        allow_serial_mismatch: bool = False,
    ) -> str | None: ...
    @property
    def schema_version(self) -> int: ...
    @property
    def serial(self) -> str: ...
    @property
    def firmware(self) -> str: ...
    def color_camera(self) -> dict[str, object]: ...
    def ir_camera(self) -> dict[str, object]: ...
    def depth_to_color(self) -> dict[str, object]: ...
    def depth_correction(self) -> dict[str, object] | None: ...
    def quality_metrics(self) -> dict[str, object] | None: ...
    def provenance(self) -> dict[str, str]: ...

class NativeProjectiveRegistrationHandle:
    def __init__(
        self,
        profile: NativeCalibrationProfileHandle,
        target: ProjectiveCameraModel,
        options: ProjectiveRegistrationOptions,
    ) -> None: ...
    def target_camera(self) -> dict[str, object]: ...
    def options(self) -> dict[str, object]: ...
    def apply(self, depth: NativeFrame, output: NativeFrame) -> None: ...

class NativeRecordingWriterHandle:
    def __init__(self, path: str, queue_capacity: int = 32) -> None: ...
    @property
    def _listener_address(self) -> int: ...
    @property
    def is_open(self) -> bool: ...
    @property
    def last_error(self) -> str: ...
    def publish_calibration(self, device: NativeDeviceHandle) -> None: ...
    def set_calibration_profile(
        self,
        profile: NativeCalibrationProfileHandle,
        allow_serial_mismatch: bool = False,
    ) -> None: ...
    def statistics(self) -> dict[str, int]: ...
    def close(self) -> None: ...

class NativeRegistrationHandle:
    def __init__(
        self, ir_params: IrCameraParams, color_params: ColorCameraParams
    ) -> None: ...
    def apply_point(self, dx: int, dy: int, dz: float) -> tuple[float, float]: ...
    def apply(
        self,
        rgb: NativeFrame,
        depth: NativeFrame,
        undistorted: NativeFrame,
        registered: NativeFrame,
        enable_filter: bool = True,
        bigdepth: NativeFrame | None = None,
        color_depth_map: npt.NDArray[np.int32] | None = None,
    ) -> None: ...
    def undistort_depth(self, depth: NativeFrame, undistorted: NativeFrame) -> None: ...
    def point_xyz(
        self, undistorted: NativeFrame, row: int, column: int
    ) -> tuple[float, float, float]: ...
    def points_xyz(
        self, undistorted: NativeFrame, pixels: npt.NDArray[np.int32]
    ) -> npt.NDArray[np.float32]: ...
    def build_color_to_depth_map(
        self,
        undistorted: NativeFrame,
        depth_to_color: npt.NDArray[np.int32],
        color_to_depth: npt.NDArray[np.int32],
    ) -> None: ...
    def lift_normalized(
        self,
        undistorted: NativeFrame,
        color_to_depth: npt.NDArray[np.int32],
        normalized_xy: npt.NDArray[np.float32],
        primary_radius: int,
        fallback_radius: int,
        cluster_span_mm: float,
    ) -> tuple[
        npt.NDArray[np.float32],
        npt.NDArray[np.bool_],
        npt.NDArray[np.int32],
    ]: ...
    def point_xyz_rgb(
        self, undistorted: NativeFrame, registered: NativeFrame, row: int, column: int
    ) -> tuple[float, float, float, int, int, int]: ...

def default_logger_level() -> int: ...
def logger_level_name(level: int) -> str: ...
def global_logger_level() -> int | None: ...
def set_global_log_level(level: int | None = None) -> None: ...
